### ISSUE TITLE
CRUD 및 프로그램 기능 정의

### ISSUE THREAD

**Issue by junglesub** [junglesub/hgu-oss-miniproject#1]
@GwonYuri 학우님 아이디어:

- [ ] 메뉴 선택(수입  or 지출, c,r,u,d, 등등)
- [x] 수입, 지출 항목 추가 - C (담당: @GwonYuri)
- [x] 수입 , 지출 항목 확인 - R (담당: @GwonYuri)
- [x] 수입, 지출 항목 변경 - U (담당: @GwonYuri)
- [x] 수입, 지출 항목 삭제 - D (담당: @junglesub)
- [ ] ~~수입 검색 기능(항목별 내역과 총합 출력)~~
- [ ] ~~지출 검색 기능(항목별 내역과 총합 출력)~~
- [ ] ~~수입, 지출, 수익 확인 (sum)~~
- [x] 특정 월 지출, 수입 내역 검색 (담당: @junglesub)
- [x] 항목별 검색 (담당: @GwonYuri) 
- [x] 결제 수단으로 검색 (담당: @junglesub)

@junglesub 학우님 아이디어:

- [ ] ~~최근에 추가된 N개 출력~~
- [x] ~원 이하, ~원 이상 금액의 지출/수입 내역 검색 (담당: @GwonYuri)
- [ ] ~~마지막으로 추가한 항목 삭제~~
- [ ] ~~마지막으로 추가한 항목 수정~~
- [ ] ~~모든 기록 출력~~
- [ ] ~~모든 기록 삭제~~

그외

- [x] 저장 (담당: @junglesub)
- [x] 불러오기  (담당: @junglesub)

**Comment by GwonYuri** [comment]
4가지 검색 기능
1. 월간 내역 확인
2. 항목별 내역 확인
3. 금액별 내역 확인

**Comment by GwonYuri** [comment]
struct 정의에 필요한 변수
1. 일자
2. 구분(수입/지출)
3. 금액
4. 결제수단

**Comment by junglesub** [comment]
> struct 정의에 필요한 변수
> 
> 1. 일자 [char[]]
> 2. 구분(수입/지출) [char]
> 3. 금액 [int]
> 4. 결제수단 [char]

일자를 string 으로 보관할경우 range 검색이 어려울 수 있습니다!

**Comment by GwonYuri** [comment]
기능 분담

권유리
1. RE
2.

유정섭
1.

**Comment by GwonYuri** [comment]
typedef struct {
 char date[20];
 char management_type[30];
 int price;
 char method[20];
} Record;

**Comment by GwonYuri** [comment]
int createRecord(Record *r); // 수입/지출 기록을 추가하는 함수
void readRecord(Record *r); // 수입/지출 기록을 읽는 함수
int updateRecord(Record *r); // 수입/지출 기록을 수정하는 함수

int selectMenu();
void listRecord(Record *r, int record_num);
int selectDataNo(Record *r, int record_num);

**Comment by junglesub** [comment]
저도 구현하고 Push 했습니다.

c3b5ca760024ae54237f7d4f52f846a481632634

**Comment by junglesub** [comment]
cc2e7f0547a4152735ae3b8b75ebe6ef92d84778
구현 완료 되었습니다.
