### ISSUE TITLE
CRUD 기능과 검색 기능 헤더파일을 각각 따로 만들까요?

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#18]
CRUD 기능과 검색 기능 헤더파일을 각각 따로 만들어서 관리하면 더 깔끔할 것 같은데 어떠세요?

**Comment by junglesub** [comment]
네 좋아요. 특별히 9주차는 `검색 기능 및 파일 저장, 읽어보기 기능을 제외한 모든 함수 구현`만 하면 되니깐 그것만 따로 만들까?

**Comment by GwonYuri** [comment]
CRUD함수는 CRUD.h로, 검색기능 포함한 나머지 함수는 search.h로, main함수는 main.c로 지정할까요?

**Comment by junglesub** [comment]
그냥 하지 맙시다! 한 파일에 하는걸로 해요~
