### ISSUE TITLE
Read 기능 구현

### ISSUE THREAD

**Issue by junglesub** [junglesub/hgu-oss-miniproject#19]
Read 는 제가 구현 할게요 학우님은 Create Update 만 해주세요!

_Originally posted by @junglesub in https://github.com/junglesub/hgu-oss-miniproject/issues/6#issuecomment-832452811_

**Comment by junglesub** [comment]
@GwonYuri 어떤 내역들이 있고 항목들을 출력하고 싶은지 알면 계속 진행하겠습니다.

**Comment by GwonYuri** [comment]
readRecord 함수에서 category와 type에 저장된 int값과 char값이 어떤 내용인지 사용자가 알 수 있도록 변환해주는 작업이 필요할 것 같습니다.
추가해주시면 좋을 것 같아요!

**Comment by junglesub** [comment]
#38 구현 완료 했습니다!
