### ISSUE TITLE
WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가

### ISSUE THREAD

**Issue by junglesub** [junglesub/hgu-oss-miniproject#20]

**Comment by junglesub** [comment]
추가 완료 했습니다.

https://github.com/junglesub/hgu-oss-miniproject/wiki/Usuage

확인해주세요.

**Comment by GwonYuri** [comment]
C,R,D는 실행했으나 Update에 해당하는 실행과 설명 부분이 빠진것 같습니다. Wiki 수정과 /screenshots 폴더 이미지 재업로드 부탁드립니다.

**Comment by GwonYuri** [comment]
/screenshots 폴더 이미지 이름도 create, read(one record), update, delete, selectMenu, listRecord(all record)로 해주시면 좋을 것 같습니다!

**Comment by junglesub** [comment]
새로운 이미지로 수정 완료 했습니다.
