### ISSUE TITLE
struct 수정 필요합니다.

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#21]
수입 또는 항목을 입력받는 management_type 변수는 있는 반면, 수입 또는 항목의 변수를 입력받는 항목 변수가 없습니다.
변수 이름 적당히 수정해서 항목 변수 추가하면 좋을 것 같습니다.
그리고 management_type은 수입 지출 두가지 밖에 없으니까 수입일 때 0, 지출일 때 1 int로 입력받는 건 어떨까요?

**Comment by junglesub** [comment]
네 알겠습니다
