### ISSUE TITLE
수입/ 지출 항목 선정

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#25]
기업의 연간 수입,지출 항목 선정이 다소 어려운 것 같습니다.
가정의 연간 수입지출서로 바꾸는게 좋을 것 같습니다.
<img width="635" alt="스크린샷 2021-05-05 오후 4 24 05" src="https://user-images.githubusercontent.com/70666097/117108670-7bf55800-adbe-11eb-9826-30bc37d60bb3.png">

항목 어떤것으로 정하면 좋을까요?

**Comment by junglesub** [comment]
**지출:** 식비, 월세, 공과금, 교통비/통신비, 문화생활비, 교육비, 저축, 기타.

**Comment by junglesub** [comment]
**소득:**  근로소득, 금융소득, 기타소득

**Comment by junglesub** [comment]
미래의 @junglesub - #20 위키에 추가하는거 잊지 말아주세요.

**Comment by GwonYuri** [comment]
오! 깔끔하고 좋은 것 같아요! 이렇게 바로 해도 될 것 같습니다!

**Comment by junglesub** [comment]
@GwonYuri - README.md 파일 꼭 수정해주세요!

**Comment by junglesub** [comment]
@junglesub WIKI Update 필요합니다. #20

**Comment by GwonYuri** [comment]
확인했습니다.
