### ISSUE TITLE
README.md 에 있는 이미지 파일이 깨졌습니다

### ISSUE THREAD

**Issue by junglesub** [junglesub/hgu-oss-miniproject#4]
@GwonYuri 학우님이 준비하신 `README.md` 파일에 있는 이미지 파일이 깨졌습니다. 다운 받으셔서 repo 에 업로드 하는 방법은 어떨까요?

이미지 주소가 임시 주소여서 더이상 존재하지 않는 것 같습니다!

**Comment by GwonYuri** [comment]
피드백 감사합니다. 수정했는데 확인부탁드립니다!

**Comment by junglesub** [comment]
8e3de75a5642d6d304dc22845411b946005673a4

빠른 수정 감사합니다!
