### ISSUE TITLE
Wiki 작성(작성되어야 할 내용 포함)

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#47]
Wiki에 포함되어야 할 내용입니다. 이후에 차근차근 추가해나가면 좋을 것 같습니다.

mini project 주제 및 설명
각 함수 담당자 및 개발일정
각 함수의 기능에 대한 간단한 설명
그외 필요한 정보들.

**Comment by junglesub** [comment]
@GwonYuri 
늦은 시간까지 감사합니다.

학우님께서 Mini Project 주제 설명과 개발 일정을 맡아주시고, 제가 함수의 기능에 대한 간단한 설명을 하는 것이 어떨까요?

**Comment by junglesub** [comment]
@GwonYuri 이 이슈 이번주까지 완성해야하는 것 아니나요? 왜 Week 11 태그가 걸려있는지 궁금합니다!

**Comment by GwonYuri** [comment]
<img width="766" alt="스크린샷 2021-05-09 오후 2 26 46" src="https://user-images.githubusercontent.com/70666097/117561541-a141d900-b0d2-11eb-9223-dae964e54df0.png">

<img width="629" alt="스크린샷 2021-05-09 오후 2 27 40" src="https://user-images.githubusercontent.com/70666097/117561548-bb7bb700-b0d2-11eb-8071-83664897e60d.png">

최종까지 Wiki 작성하면 되는 것으로 이해했습니다!

**Comment by junglesub** [comment]
감사합니다!

**Comment by GwonYuri** [comment]
WIKI 작성하느라 수고하셨습니다!
