### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#48]
피드백 부탁드립니다.

**Comment by junglesub** [comment]
> Wiki 링크 추가 깜빡했습니다. 수정하겠습니다.

위키 링크만 추가하시면 될 것 같습니다. 수고 많으셨습니다!

**Comment by GwonYuri** [comment]
<img width="1062" alt="스크린샷 2021-05-09 오후 2 56 33" src="https://user-images.githubusercontent.com/70666097/117562027-cc2e2c00-b0d6-11eb-8514-84cbe238fad8.png">

Wiki link를 추가했는데 해당 url로 접속이 안됩니다. 혹시 어떤 문제인지 아실까요?

**Comment by junglesub** [comment]
> <img alt="스크린샷 2021-05-09 오후 2 56 33" width="1062" src="https://user-images.githubusercontent.com/70666097/117562027-cc2e2c00-b0d6-11eb-8514-84cbe238fad8.png">
> 
> Wiki link를 추가했는데 해당 url로 접속이 안됩니다. 혹시 어떤 문제인지 아실까요?

그 링크는 git clone 할때 사용하는 링크이고 https://github.com/junglesub/hgu-oss-miniproject/wiki 링크 사용하셔야할 것 같습니다.

**Comment by GwonYuri** [comment]
감사합니다. 수정 완료했습니다!
