### ISSUE TITLE
delete 함수 수정

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#54]
delete 함수에서 배열의 시작 0에 맞추어 파라미터를 no-1로 했었는데, return 할때는 다시 값을 +1로 수정해줘야 할 것 같습니다.
확인부탁드립니다.

**Comment by junglesub** [comment]
#53 롤백이 취소가 되었기 때문에 이미 수정해주신 것을 사용하겠습니다. 감사합니다.
