### ISSUE TITLE
4가지 검색기능 맥락 통일

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#69]
4가지 검색기능을 상의해서 맥락을 통일하면 좋을 것 같습니다.

**Comment by GwonYuri** [comment]
4가지 검색 기능 모두 파라미터로 수입 또는 지출을 입력받아 해당하는 관리 항목의 특정 내용을 검색하는 것으로 구현하면 좋을 것 같습니다!

**Comment by junglesub** [comment]
네 작업 시작하겠습니다!

수정될 함수는 "날짜 검색", "결제수단" 입니다.
