### ISSUE TITLE
저희 포인터 배열을 사용할까요?

### ISSUE THREAD

**Issue by junglesub** [junglesub/hgu-oss-miniproject#7]
지금은 일반 배열로 받고 있습니다. 

메모리를 더 효율적으로 관리하기 위해서 포인터배열 (더블포인터) 방식으로 데이터 struct 바꾸는게 어떨까요?

**Comment by GwonYuri** [comment]
네! 포인터배열로 작성하면 좋을 것 같아요! 좋은 의견 감사합니다.

**Comment by junglesub** [comment]
수정완료
