### ISSUE TITLE
read 기능 수정

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#71]
현재 read 기능이 특정 기록 내용 읽기로 되어있는데, 전체 기록 또한 특정 항목 내용에서 보여지는 내용을 다 보여주고 있어서 중복된다고 생각됩니다.
read 함수를 현재 listRecord로 대체하는 건 어떠신가요?

**Comment by junglesub** [comment]
사실 원래 read 기능이 있는 이유는 다 보여주지 않은 상태에서 특정 아이디를 알경우에 해당 기록을 바로 접근하고 싶어서 입니다. 따라서 삭제하는 것보다는 먼저 전체 기록을 보여주지 않는 방법은 어떨까요?

**Comment by junglesub** [comment]
그래서 그냥 위에 함수 다보여주는 그 함수 있잖아요 그걸 삭제하고 몇번부터 몇번까지 있는지 (`count`) 만 보여주는게 어떨까요?

**Comment by junglesub** [comment]
그래서 1번부터 10번까지 선택 가능 이런식으로

**Comment by junglesub** [comment]
유노왓암쎄잉?

**Comment by junglesub** [comment]
어떻게 생각하시나요 @GwonYuri

**Comment by GwonYuri** [comment]
음,,, 저는 read 함수와 listRecord 함수를 바꾸는 게 좋을 것 같습니다.

**Comment by junglesub** [comment]
그렇게 하시죠!

**Comment by junglesub** [comment]
제가 진행하겠습니다.
