### ISSUE TITLE
전체적인 피드백 사항

### ISSUE THREAD

**Issue by GwonYuri** [junglesub/hgu-oss-miniproject#73]
보시고 피드백 사항이 있으면 남겨주세요!

**Comment by junglesub** [comment]
@GwonYuri 
유저 메세지 받는거 정리하고 스크린샷 찍고 위키 업데이트 하면 될듯 합니다.
텍스트 문구 부적절한게 있으면 편하게 바꿔주세요!

**Comment by GwonYuri** [comment]
searchItem 항목별 내역 검색 함수에서 return readRecord(r[i], count + 1);에 오류가 있습니다. 수정부탁드립니다.

**Comment by GwonYuri** [comment]
위키 업데이트가 필요합니다! 
mini project 주제 및 설명, 각 함수 담당자 및 개발일정은 제가 맡고 함수 기능 설명에 해당하는 내용 업데이트 부탁드립니다.

**Comment by GwonYuri** [comment]
피드백 모두 반영하여 수정 완료했습니다. 수고하셨습니다!
